### Reading data

In [1]:
import pandas as pd
from sclibrary.read_data import GraphDataReader

data_folder = 'data/london_street'

#### Option 1: CSV

In [2]:
# read csv
filename = data_folder + '/LondonEdges.csv'
G = GraphDataReader.read_csv(filename=filename, delimeter=" ", src_col='Source', dest_col='Target', weight_col='distance')
simplices = G.simplicies
simplices

[[3],
 [7],
 [9],
 [18],
 [23],
 [25],
 [38],
 [44],
 [45],
 [39],
 [27],
 [24],
 [20],
 [12],
 [8],
 [6],
 [1],
 [16],
 [35],
 [40],
 [46],
 [42],
 [37],
 [28],
 [30],
 [33],
 [34],
 [26],
 [36],
 [48],
 [43],
 [47],
 [57],
 [60],
 [66],
 [4],
 [10],
 [13],
 [11],
 [15],
 [17],
 [5],
 [21],
 [32],
 [31],
 [51],
 [50],
 [49],
 [54],
 [55],
 [52],
 [59],
 [61],
 [58],
 [62],
 [64],
 [65],
 [69],
 [56],
 [2],
 [14],
 [19],
 [22],
 [29],
 [41],
 [53],
 [63],
 [70],
 [68],
 [72],
 [74],
 [75],
 [71],
 [73],
 [67],
 [80],
 [78],
 [77],
 [76],
 [81],
 [82],
 [79],
 [3, 7],
 [3, 6],
 [7, 9],
 [7, 8],
 [9, 18],
 [9, 12],
 [18, 23],
 [18, 20],
 [23, 25],
 [23, 24],
 [25, 38],
 [25, 27],
 [38, 44],
 [38, 39],
 [44, 45],
 [45, 40],
 [45, 46],
 [39, 35],
 [39, 40],
 [27, 24],
 [27, 35],
 [27, 28],
 [24, 20],
 [24, 26],
 [24, 36],
 [24, 21],
 [20, 16],
 [12, 8],
 [12, 16],
 [8, 6],
 [8, 10],
 [6, 1],
 [1, 4],
 [16, 21],
 [35, 37],
 [40, 42],
 [46, 42],
 [46, 48],
 [46, 60],
 [42, 37],
 [37, 28],
 [

#### Option 2: Incidence matrices, B1 & B2

In [108]:
# read B1, B2
B1_filename = f'{data_folder}/B1.csv'
B2_filename = f'{data_folder}/B2.csv'
G = GraphDataReader.read_incidence_matrix(B1_filename, B2_filename)
simplices = G.simplicies
simplices

[[0],
 [1],
 [2],
 [3],
 [4],
 [0, 1],
 [0, 2],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 3],
 [3, 4],
 [0, 1, 2],
 [1, 2, 3],
 [1, 3, 4]]

### Simplical Complex Analysis

In [3]:
from sclibrary.simplicial_complex import SimplicialComplexNetwork

sc = SimplicialComplexNetwork(simplices, pos=None)
L1 = sc.hodge_laplacian_matrix(rank=1)
L1L = sc.lower_laplacian_matrix(rank=1)
L1U = sc.upper_laplacian_matrix(rank=1)
L1

array([[ 2.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  2.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2.,  0., -1.],
       [ 0.,  0.,  0., ...,  0.,  3.,  1.],
       [ 0.,  0.,  0., ..., -1.,  1.,  2.]], dtype=float32)

### Eigendecompostion

In [117]:
import numpy as np
from sclibrary.eigendecomposition import get_harmonic_eigenvectors, get_curl_eigenvectors, get_gradient_eigenvectors

u_h, eigenvecs_h = get_harmonic_eigenvectors(L1)
u_c, eigenvecs_c = get_curl_eigenvectors(L1U)
u_g, eigenvecs_g = get_gradient_eigenvectors(L1L)

In [19]:
L = 10
lam_l = np.diag(L1)
Phi_G = np.array([lam_l ** (l - 1) for l in range(1, L + 1)]).T
Phi_G

array([[1.00000e+00, 2.00000e+00, 4.00000e+00, 8.00000e+00, 1.60000e+01,
        3.20000e+01, 6.40000e+01, 1.28000e+02, 2.56000e+02, 5.12000e+02],
       [1.00000e+00, 2.00000e+00, 4.00000e+00, 8.00000e+00, 1.60000e+01,
        3.20000e+01, 6.40000e+01, 1.28000e+02, 2.56000e+02, 5.12000e+02],
       [1.00000e+00, 3.00000e+00, 9.00000e+00, 2.70000e+01, 8.10000e+01,
        2.43000e+02, 7.29000e+02, 2.18700e+03, 6.56100e+03, 1.96830e+04],
       [1.00000e+00, 4.00000e+00, 1.60000e+01, 6.40000e+01, 2.56000e+02,
        1.02400e+03, 4.09600e+03, 1.63840e+04, 6.55360e+04, 2.62144e+05],
       [1.00000e+00, 3.00000e+00, 9.00000e+00, 2.70000e+01, 8.10000e+01,
        2.43000e+02, 7.29000e+02, 2.18700e+03, 6.56100e+03, 1.96830e+04],
       [1.00000e+00, 3.00000e+00, 9.00000e+00, 2.70000e+01, 8.10000e+01,
        2.43000e+02, 7.29000e+02, 2.18700e+03, 6.56100e+03, 1.96830e+04],
       [1.00000e+00, 3.00000e+00, 9.00000e+00, 2.70000e+01, 8.10000e+01,
        2.43000e+02, 7.29000e+02, 2.18700e+03

### Extra

In [24]:
from scipy.linalg import pinv

# Calculate alpha
alpha = pinv(Phi_G) @ np.concatenate([np.array([1]), np.zeros(len(lam_l)-1)])

# Build the filter
H = np.zeros((7, 7))
for l in range(1, L+1):
    H += alpha[l-1] * L1L**(l-1)
    
H

array([[ 4.99989013e-01,  2.52210576e-02, -8.41018630e-03,
        -8.41018630e-03, -8.41018630e-03,  4.01874218e-04,
         4.01874218e-04],
       [ 2.52210576e-02,  4.99989013e-01,  2.52210576e-02,
         4.01874218e-04,  4.01874218e-04, -8.41018630e-03,
         4.01874218e-04],
       [-8.41018630e-03,  2.52210576e-02,  4.99989013e-01,
         2.52210576e-02,  2.52210576e-02, -8.41018630e-03,
         4.01874218e-04],
       [-8.41018630e-03,  4.01874218e-04,  2.52210576e-02,
         4.99989013e-01,  2.52210576e-02,  2.52210576e-02,
        -8.41018630e-03],
       [-8.41018630e-03,  4.01874218e-04,  2.52210576e-02,
         2.52210576e-02,  4.99989013e-01,  4.01874218e-04,
         2.52210576e-02],
       [ 4.01874218e-04, -8.41018630e-03, -8.41018630e-03,
         2.52210576e-02,  4.01874218e-04,  4.99989013e-01,
        -8.41018630e-03],
       [ 4.01874218e-04,  4.01874218e-04,  4.01874218e-04,
        -8.41018630e-03,  2.52210576e-02, -8.41018630e-03,
         4.9998901

In [137]:
# flow geenration
flow = np.random.rand(L1.shape[0], 1)
print("flow", flow)
# analyze frequency components
flow_h = u_h.T @ flow
flow_g = u_g.T @ flow
flow_c = u_c.T @ flow
print("flow_h", flow_h)
print("flow_g", flow_g)
print("flow_c", flow_c)

flow [[0.31004]
 [0.03894]
 [0.10792]
 [0.1813 ]
 [0.45826]
 [0.18989]
 [0.53967]]
flow_h [[ 0.18668]
 [-0.67182]
 [-0.24841]
 [ 0.21872]
 [-0.21247]
 [-0.18961]
 [ 0.05168]]
flow_g [[ 0.18668]
 [-0.67182]
 [-0.24841]
 [ 0.21872]
 [ 0.21247]
 [ 0.16781]
 [-0.18515]]
flow_c [[ 0.1434 ]
 [-0.18961]
 [-0.05168]
 [-0.40154]
 [ 0.37462]
 [ 0.31004]
 [ 0.03894]]
