In [1]:

import numpy as np
from sclibrary import dataset_loader
from sclibrary import SCPlot

sc, coordinates = dataset_loader.load_paper_data()

# create a plot
scplot = SCPlot(sc, coordinates)

In [3]:
L1 = sc.hodge_laplacian_matrix(rank=1).toarray()
L1u = sc.upper_laplacian_matrix(rank=1).toarray()
Le = sc.lower_laplacian_matrix(rank=1).toarray()

In [4]:
from sclibrary.utils.eigendecomposition import get_eigendecomposition
u1, eigenvals = get_eigendecomposition(L1)
u1L, eigenvalsL = get_eigendecomposition(Le)
u1u, eigenvalsu = get_eigendecomposition(L1u)

In [5]:
u1

array([[ 0.06889728,  0.13607139,  0.5       , -0.48619685,  0.        ,
         0.09433983,  0.46687335, -0.35355339, -0.36745652, -0.05878212],
       [ 0.13779456, -0.18544569,  0.        , -0.06525469,  0.        ,
         0.31280028,  0.10648241,  0.70710678, -0.47395312,  0.32946974],
       [-0.20669185, -0.29740454, -0.5       ,  0.3267199 ,  0.        ,
         0.02961399,  0.27923198, -0.35355339, -0.53557877, -0.1462567 ],
       [ 0.06889728, -0.32151708,  0.5       ,  0.42094216,  0.        ,
         0.21846044, -0.36039095, -0.35355339, -0.10649659,  0.38825186],
       [-0.34448641, -0.11195885,  0.5       ,  0.39197459,  0.        ,
        -0.28318629,  0.17274957,  0.35355339, -0.06162565, -0.47572643],
       [ 0.55117825, -0.59076521,  0.        , -0.10910526,  0.        ,
         0.21460989,  0.04279641,  0.        ,  0.21684759, -0.49028892],
       [-0.55117825, -0.51395109,  0.        , -0.26664402,  0.        ,
         0.08504378,  0.29986768,  0.        

In [14]:
f = u1 @ np.ones(u1.shape[1])
f_h = u1 @ sc.get_component_coefficients(component="harmonic")
f_g = u1 @ sc.get_component_coefficients(component="gradient")
f_c = u1 @ sc.get_component_coefficients(component="curl")

In [16]:
from sclibrary.filters import LSFilterDesign

ls = LSFilterDesign(sc)

ls.subcomponent_extraction_type_one(f=f, component="gradient", L=50)

Filter size: 0 - Error: 0.6324555320336753
Filter size: 1 - Error: 0.5956108987452714
Filter size: 2 - Error: 0.5946425592258179
Filter size: 3 - Error: 0.5760676876125795
Filter size: 4 - Error: 0.5496391608198462
Filter size: 5 - Error: 0.5311014693141679
Filter size: 6 - Error: 0.4919951869407741
Filter size: 7 - Error: 0.49062817330043024
Filter size: 8 - Error: 0.11842737940382456
Filter size: 9 - Error: 1.5608710002763043e-06
Filter size: 10 - Error: 1.392164004565205e-06
Filter size: 11 - Error: 3.732146492119331e-07
Filter size: 12 - Error: 6.363514840969503e-07
Filter size: 13 - Error: 3.1334816502647597e-07
Filter size: 14 - Error: 8.575767622612958e-07
Filter size: 15 - Error: 1.044411185370235e-05
Filter size: 16 - Error: 5.8520648981705455e-05
Filter size: 17 - Error: 0.000305132980726761
Filter size: 18 - Error: 0.0028272804708893316
Filter size: 19 - Error: 0.18771791542099436
Filter size: 20 - Error: 0.41104036344493966
Filter size: 21 - Error: 0.4092251751773657
Filter

In [18]:
ls.subcomponent_extraction_type_two(f=f, component="gradient", L=50)

Filter size: 0 - Error: 0.7142857142857134
Filter size: 1 - Error: 0.4564354645876381
Filter size: 2 - Error: 0.2838953890353672
Filter size: 3 - Error: 0.13497761822032994
Filter size: 4 - Error: 0.04173370294665379
Filter size: 5 - Error: 0.0029883850147950346
Filter size: 6 - Error: 2.4246260709374354e-12
Filter size: 7 - Error: 1.6490021568543975e-11
Filter size: 8 - Error: 8.000352454161464e-11
Filter size: 9 - Error: 2.1053322935212313e-10
Filter size: 10 - Error: 1.6578709006739788e-09
Filter size: 11 - Error: 1.3048665023637588e-08
Filter size: 12 - Error: 3.533749080764176e-08
Filter size: 13 - Error: 2.0790454316158968e-07
Filter size: 14 - Error: 1.4866792571436916e-06
Filter size: 15 - Error: 4.8094484231498216e-06
Filter size: 16 - Error: 3.539939721337782e-05
Filter size: 17 - Error: 0.0003056012833850979
Filter size: 18 - Error: 0.0016568045369564643
Filter size: 19 - Error: 0.2991603025240874
Filter size: 20 - Error: 0.4082469586928006
Filter size: 21 - Error: 0.4082478

In [2]:
f0 = np.array([-0.0689, -0.1378, 0.2067, -0.0689, 0.3445, -0.5512, 0.5512, 0.3675, 0.1837, -0.1837])
f = np.array([-1.4188, 2.8971, 0.9321, -0.1320, 1.0592, -0.7561, 0.4270, 1.8571, 1.5928, 1.2335])

In [3]:
from sclibrary.filters import EdgeFlowDenoising

muvals = [1e-2, 5e-2, 1e-1, 2.5e-1, 5e-1, 1, 2.5, 5, 10, 25, 50, 100]

edf = EdgeFlowDenoising(sc)
edf.denoise(f=f, f_true=f0, mu_vals=muvals, p_choice="L1")

mu: 0.01, error: 4.13878995554169
mu: 0.05, error: 3.6624649566608105
mu: 0.1, error: 3.2249814188202164
mu: 0.25, error: 2.4457460687536674
mu: 0.5, error: 1.8382890906211293
mu: 1, error: 1.3366302011773288
mu: 2.5, error: 0.9089994065189698
mu: 5, error: 0.754349083535742
mu: 10, error: 0.6929078089653214
mu: 25, error: 0.6705679235314629
mu: 50, error: 0.6669087225040363
mu: 100, error: 0.6659488364043868


In [4]:
edf.history["frequency_responses"][-1]

array([1.        , 0.01213078, 0.00497512, 0.00427714, 0.00332226,
       0.00300851, 0.00277155, 0.00249377, 0.00223837, 0.00181881])

In [1]:

import numpy as np
from sclibrary import dataset_loader
from sclibrary import SCPlot

sc, coordinates = dataset_loader.load_paper_data()

# create a plot
scplot = SCPlot(sc, coordinates)

In [2]:
f0 = np.array([-0.0689, -0.1378, 0.2067, -0.0689, 0.3445, -0.5512, 0.5512, 0.3675, 0.1837, -0.1837])
f = np.array([-0.1711, -0.3792, 0.5259, 0.2440, -0.5204, -0.5812, 0.3863, 0.9952, 1.2770, 0.9255])


In [6]:
from sclibrary.filters import GridBasedFilterDesign

gbf = GridBasedFilterDesign(sc)

gbf.denoise(f=f, f_true=f0, p_choice="L1", L=15)

gbf.history["frequency_responses"][-1]

Filter size: 0 - Error: 1.1145220187619012
Filter size: 1 - Error: 0.9174238859255925
Filter size: 2 - Error: 0.7980897263179785
Filter size: 3 - Error: 0.8097442535275531
Filter size: 4 - Error: 0.8105673351540454
Filter size: 5 - Error: 0.8081901125729355
Filter size: 6 - Error: 0.8084003631752389
Filter size: 7 - Error: 0.808413695106161
Filter size: 8 - Error: 0.8083988982483638
Filter size: 9 - Error: 0.8084065150260697
Filter size: 10 - Error: 0.8083506099008334
Filter size: 11 - Error: 0.8080688641361645
Filter size: 12 - Error: 0.8067575236384018
Filter size: 13 - Error: 0.8009861267673423
Filter size: 14 - Error: 0.7891291622989668


array([1.        , 0.70390008, 0.49423139, 0.45717316, 0.40442155,
       0.34937557, 0.34363678, 0.43143647, 0.04911948, 0.25628698])