In [1]:
import os

# set the current working directory
curr_path = os.getcwd().split("/")[:-1]
curr_path = "/".join(curr_path)
os.chdir(curr_path)
os.getcwd()

'/Users/irtaza.hashmi@futurice.com/Desktop/Thesis/sc-graph-library'

In [2]:
import pandas as pd
import numpy as np

In [3]:
B1_filename = "data/test_dataset/B1_chicago_sketch.csv"
#B1_filename = "data/blah/B1.csv"

B1 = pd.read_csv(B1_filename, header=None).to_numpy()

def extract_edges(B1):
    num_edges = B1.shape[1]
    
    nodes = set()
    edges = []
    
    for j in range(num_edges):
        col = B1[:,j]
        from_node = np.where(col == -1)[0][0]
        to_node = np.where(col == 1)[0][0]
        
        nodes.add(from_node)
        nodes.add(to_node)

        edges.append((from_node, to_node))

    # sort
    nodes = list(nodes)
    nodes.sort()
    edges.sort()
    edges = [tuple(edge) for edge in edges]
    return nodes, edges

nodes, edges = extract_edges(B1)
print(len(edges))
edges

1088


[(2, 0),
 (2, 1),
 (3, 0),
 (4, 3),
 (5, 4),
 (6, 5),
 (7, 6),
 (8, 7),
 (9, 8),
 (10, 9),
 (11, 10),
 (12, 10),
 (13, 12),
 (14, 13),
 (15, 10),
 (16, 15),
 (17, 16),
 (18, 17),
 (19, 18),
 (20, 19),
 (21, 20),
 (22, 21),
 (23, 22),
 (24, 23),
 (25, 24),
 (26, 25),
 (27, 26),
 (28, 27),
 (29, 28),
 (31, 30),
 (32, 31),
 (33, 32),
 (34, 33),
 (35, 34),
 (36, 35),
 (37, 36),
 (38, 37),
 (39, 38),
 (40, 39),
 (41, 40),
 (42, 41),
 (43, 40),
 (44, 43),
 (45, 44),
 (46, 45),
 (47, 46),
 (48, 47),
 (49, 48),
 (50, 49),
 (51, 50),
 (52, 51),
 (53, 38),
 (53, 52),
 (55, 54),
 (56, 55),
 (57, 56),
 (58, 57),
 (59, 58),
 (60, 59),
 (61, 60),
 (62, 61),
 (63, 62),
 (64, 63),
 (65, 62),
 (66, 65),
 (67, 66),
 (68, 67),
 (69, 68),
 (70, 69),
 (71, 70),
 (72, 71),
 (73, 72),
 (74, 73),
 (76, 75),
 (77, 76),
 (78, 77),
 (79, 70),
 (79, 78),
 (80, 70),
 (81, 80),
 (82, 81),
 (83, 82),
 (84, 83),
 (85, 84),
 (86, 85),
 (87, 85),
 (88, 87),
 (89, 88),
 (90, 89),
 (91, 90),
 (92, 91),
 (93, 92),
 (94, 9

In [4]:
B2_filename = "data/test_dataset/B2t_chicago_sketch.csv"
#B2_filename = "data/blah/B2.csv"

B2 = pd.read_csv(B2_filename, header=None).to_numpy().T

num_edges = B2.shape[0]
num_triangles = B2.shape[1]
print(num_edges, num_triangles)

# Function to extract triangles and their edges
def extract_triangles(B2):
    _, edges = extract_edges(B1)
    edges = np.array(edges)
    
    triangles = []
    for j in range(num_triangles):
        print(f"Triangle {j}")
        # Check each column of B2 for triangles
        col = B2[:, j]
        print(col)
        # get pos of 1s
        ones = np.where(col != 0)[0]
        print(ones)
        triangle = edges[ones]
        print(triangle)
        triangle = tuple(set(triangle.flatten()))
        # sort 
        triangle = tuple(sorted(triangle))
        triangles.append(triangle)
        print(triangle)
        print("-" * 50)
    
    return triangles


triangles = extract_triangles(B2)
print(len(triangles))
triangles

1088 112
Triangle 0
[0 0 0 ... 0 0 0]
[  6 262 263]
[[  7   6]
 [196   6]
 [196   7]]
(6, 7, 196)
--------------------------------------------------
Triangle 1
[0 0 0 ... 0 0 0]
[ 28 627 628]
[[ 29  28]
 [344  28]
 [344  29]]
(28, 29, 344)
--------------------------------------------------
Triangle 2
[0 0 0 ... 0 0 0]
[ 53 997 998]
[[ 55  54]
 [510  54]
 [510  55]]
(54, 55, 510)
--------------------------------------------------
Triangle 3
[0 0 0 ... 0 0 0]
[ 62 443 444]
[[ 64  63]
 [266  63]
 [266  64]]
(63, 64, 266)
--------------------------------------------------
Triangle 4
[0 0 0 ... 0 0 0]
[139 437 438]
[[137  64]
 [264  64]
 [264 137]]
(64, 137, 264)
--------------------------------------------------
Triangle 5
[0 0 0 ... 0 0 0]
[ 75 918 919]
[[ 78  77]
 [474  77]
 [474  78]]
(77, 78, 474)
--------------------------------------------------
Triangle 6
[0 0 0 ... 0 0 0]
[ 77 902 903]
[[ 79  78]
 [467  78]
 [467  79]]
(78, 79, 467)
-------------------------------------------------

[(6, 7, 196),
 (28, 29, 344),
 (54, 55, 510),
 (63, 64, 266),
 (64, 137, 264),
 (77, 78, 474),
 (78, 79, 467),
 (83, 84, 427),
 (84, 85, 425),
 (85, 87, 319),
 (87, 88, 319),
 (89, 115, 116),
 (92, 93, 95),
 (99, 100, 294),
 (101, 102, 243),
 (104, 105, 174),
 (117, 118, 251),
 (125, 126, 517),
 (131, 133, 282),
 (143, 144, 186),
 (144, 145, 181),
 (138, 139, 158),
 (160, 162, 164),
 (160, 164, 230),
 (161, 162, 163),
 (162, 165, 172),
 (162, 164, 165),
 (167, 168, 236),
 (170, 172, 173),
 (171, 178, 243),
 (182, 183, 184),
 (181, 182, 184),
 (181, 184, 185),
 (188, 189, 190),
 (184, 188, 249),
 (190, 191, 192),
 (191, 192, 194),
 (192, 193, 194),
 (187, 192, 193),
 (196, 198, 200),
 (203, 220, 225),
 (203, 204, 220),
 (204, 220, 221),
 (207, 224, 229),
 (207, 208, 224),
 (210, 228, 232),
 (210, 211, 228),
 (166, 226, 231),
 (166, 226, 234),
 (168, 169, 236),
 (166, 234, 237),
 (167, 234, 237),
 (183, 246, 249),
 (183, 184, 249),
 (250, 252, 254),
 (188, 190, 255),
 (272, 273, 514),
 (

In [9]:
from sclibrary.io.network_reader import read_B1

g = read_B1(B1_filename=B1_filename)
sc = g.to_simplicial_complex(triangles=triangles)

print("nodes:", len(sc.nodes))
print("edges:", len(sc.edges))
print("triangles:", len(sc.triangles))

nodes: 546
edges: 1088
triangles: 112


In [10]:
import networkx as nx

incg = nx.incidence_matrix(g, oriented=True, edgelist=edges, nodelist=nodes).toarray()
np.array_equal(incg, B1)

/var/folders/py/wfd5gjj55nx4cqtdvltb22mw0000gp/T/ipykernel_56529/3069000555.py:3: FutureWarning: incidence_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  incg = nx.incidence_matrix(g, oriented=True, edgelist=edges, nodelist=nodes).toarray()


True

In [24]:
scinc = sc.incidence_matrix(rank=1)
scinc

array([[-1., -1., -1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [27]:
scinc = sc.incidence_matrix(rank=1)

edges = sc.edges
sorted_edges = sorted(edges, key=lambda x: (x[0], x[1]))
full_columns_to_reorder = [edge[1] for edge in sorted_edges]

# Ensure all columns are accounted for in the sorting (by adding missing columns)
all_columns = set(range(scinc.shape[1]))
missing_columns = list(all_columns - set(full_columns_to_reorder))
full_columns_to_reorder += missing_columns

# Reorder all matrix columns based on the complete sorted column list
fully_reordered_matrix = scinc[:, full_columns_to_reorder]
fully_reordered_matrix


array([[-1., -1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [12]:
L0 = B1 @ B1.T
L2 = B2.T @ B2
#L1 = B1.T @ B1 + B2 @ B2.T

L0_me = sc.hodge_laplacian_matrix(rank=0)
B2 = sc.incidence_matrix(rank=2)
L2_me = B2.T @ B2

#L1_me = sc.hodge_laplacian_matrix(rank=1)

print(np.allclose(L0, L0_me))

#print(np.allclose(B2, sc.incidence_matrix(rank=2)))
print(np.allclose(L2, L2_me))

True
True
